delete from airline;      
delete from bca_billing_summary_record;
-- delete from blank_fillins;             
delete from car_rental;             
delete from cardmem_bill_sum_rcrd;
delete from detail_billing_data ;       
delete from file_header   ;             
delete from file_trailer ;              
delete from general      ;              
delete from hotel       ;               
delete from insurance    ;              
delete from mail_order   ;              
delete from petrol_or_oil ;             
delete from rail          ;             
delete from rca_bill_summ_rcrd_data   ; 
delete from restaurant            ;     
delete from retail                ;     
-- delete from sic_to_general_ledger ;     
delete from telephone_call      ;       
delete from ticket              ;       
delete from uploads_and_progress  ;     
